### PR TITLE
Signup page added

### PR DESCRIPTION
**Pull request by gokhalevedant06**
Screenshot (891)

### CODE REVIEW

**Comment by poojanV55** [comment]
Can you please add the pr in the new branch :)

**Comment by gokhalevedant06** [comment]
> Can you please add the pr in the new branch :)

I can see only 1 branch

**Comment by poojanV55** [comment]
@gokhalevedant06 Can you change the display to light mode or change the input text color .

**Comment by gokhalevedant06** [comment]
> @gokhalevedant06 Can you change the display to light mode or change the input text color .

Will change the input text color, dark mode looks better

**Review by poojanV55 — COMMENTED** [review]
Change the text i.e.: the text which is shown when we write something into the input fields. Its still dark.

**Comment by poojanV55** [comment]
Hello @gokhalevedant06  , any updates ?

**Comment by gokhalevedant06** [comment]
@poojanV55  I have changed it to white

**Comment by gokhalevedant06** [comment]
Screenshot (893)


> @poojanV55 I have changed it to white

**Pull request merged**
